language: node_js

node_js:
  - "8"

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - lab


env:
  - ALGORITHM1=MIN_MAX HEURISTIC1=REMAINING_POINTS ALGHORITM2=MIN_MAX HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=MIN_MAX HEURISTIC1=REMAINING_POINTS ALGHORITM2=MIN_MAX HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=MIN_MAX HEURISTIC1=REMAINING_POINTS ALGHORITM2=MIN_MAX HEURISTIC2=MILL_NEXT

  - ALGORITHM1=MIN_MAX HEURISTIC1=ALMOST_MILL ALGHORITM2=MIN_MAX HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=MIN_MAX HEURISTIC1=ALMOST_MILL ALGHORITM2=MIN_MAX HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=MIN_MAX HEURISTIC1=ALMOST_MILL ALGHORITM2=MIN_MAX HEURISTIC2=MILL_NEXT

  - ALGORITHM1=MIN_MAX HEURISTIC1=MILL_NEXT ALGHORITM2=MIN_MAX HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=MIN_MAX HEURISTIC1=MILL_NEXT ALGHORITM2=MIN_MAX HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=MIN_MAX HEURISTIC1=MILL_NEXT ALGHORITM2=MIN_MAX HEURISTIC2=MILL_NEXT

  - ALGORITHM1=ALPHA_BETA HEURISTIC1=REMAINING_POINTS ALGHORITM2=MIN_MAX HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=REMAINING_POINTS ALGHORITM2=MIN_MAX HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=REMAINING_POINTS ALGHORITM2=MIN_MAX HEURISTIC2=MILL_NEXT

  - ALGORITHM1=ALPHA_BETA HEURISTIC1=ALMOST_MILL ALGHORITM2=MIN_MAX HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=ALMOST_MILL ALGHORITM2=MIN_MAX HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=ALMOST_MILL ALGHORITM2=MIN_MAX HEURISTIC2=MILL_NEXT

  - ALGORITHM1=ALPHA_BETA HEURISTIC1=MILL_NEXT ALGHORITM2=MIN_MAX HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=MILL_NEXT ALGHORITM2=MIN_MAX HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=MILL_NEXT ALGHORITM2=MIN_MAX HEURISTIC2=MILL_NEXT

  - ALGORITHM1=MIN_MAX HEURISTIC1=REMAINING_POINTS ALGHORITM2=ALPHA_BETA HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=MIN_MAX HEURISTIC1=REMAINING_POINTS ALGHORITM2=ALPHA_BETA HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=MIN_MAX HEURISTIC1=REMAINING_POINTS ALGHORITM2=ALPHA_BETA HEURISTIC2=MILL_NEXT

  - ALGORITHM1=MIN_MAX HEURISTIC1=ALMOST_MILL ALGHORITM2=ALPHA_BETA HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=MIN_MAX HEURISTIC1=ALMOST_MILL ALGHORITM2=ALPHA_BETA HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=MIN_MAX HEURISTIC1=ALMOST_MILL ALGHORITM2=ALPHA_BETA HEURISTIC2=MILL_NEXT

  - ALGORITHM1=MIN_MAX HEURISTIC1=MILL_NEXT ALGHORITM2=ALPHA_BETA HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=MIN_MAX HEURISTIC1=MILL_NEXT ALGHORITM2=ALPHA_BETA HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=MIN_MAX HEURISTIC1=MILL_NEXT ALGHORITM2=ALPHA_BETA HEURISTIC2=MILL_NEXT

  - ALGORITHM1=ALPHA_BETA HEURISTIC1=REMAINING_POINTS ALGHORITM2=ALPHA_BETA HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=REMAINING_POINTS ALGHORITM2=ALPHA_BETA HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=REMAINING_POINTS ALGHORITM2=ALPHA_BETA HEURISTIC2=MILL_NEXT

  - ALGORITHM1=ALPHA_BETA HEURISTIC1=ALMOST_MILL ALGHORITM2=ALPHA_BETA HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=ALMOST_MILL ALGHORITM2=ALPHA_BETA HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=ALMOST_MILL ALGHORITM2=ALPHA_BETA HEURISTIC2=MILL_NEXT

  - ALGORITHM1=ALPHA_BETA HEURISTIC1=MILL_NEXT ALGHORITM2=ALPHA_BETA HEURISTIC2=REMAINING_POINTS
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=MILL_NEXT ALGHORITM2=ALPHA_BETA HEURISTIC2=ALMOST_MILL
  - ALGORITHM1=ALPHA_BETA HEURISTIC1=MILL_NEXT ALGHORITM2=ALPHA_BETA HEURISTIC2=MILL_NEXT


prescript: "npm i"
script: "node (./node_modules/parcel-bundler/bin/cli.js DUPA=HEHE index.html | grep .js | tail -n 1 | cut -d' ' -f1 | node)"
