export enum GameMoveResult {
    SUCCESSFUL_MOVE = 'SUCCESSFUL_MOVE',
    FIRST_MOVE_PART = 'FIRST_MOVE_PART',
    RESTART_MOVE = 'RESTART_MOVE',
    CANNOT_MOVE = 'CANNOT_MOVE',
    MILL = 'MILL',
    OPPONENT_DESTROYED = 'OPPONENT_DESTROYED',
    INVALID_MILL_MOVE = 'INVALID_MILL_MOVE',
}

export const NEXT_PLAYER_RESULTS = [GameMoveResult.SUCCESSFUL_MOVE, GameMoveResult.OPPONENT_DESTROYED];
